### ISSUE TITLE
[macOS] Estimated time to transcribe is not accurate

### ISSUE THREAD

**Issue by rsquizz** [campionfellin/CLOxIssueTracker#11]
**Describe the bug**
I was pleasantly surprised to discover that when transcribing two m4a audio files, each about 20 minutes long, that the estimated time of about 20 minutes was a major overestimate - it actually took CLOx under 3 minutes to transcribe each file, using US English offline transcription (I think it was offline - I didn't disable my internet and I didn't see a message that it was being transcribed online). I don't know if I'm allowed to attach the files here, but you can download the .m4a files [here](https://osf.io/xfrkh/) and [here](https://osf.io/tc9jf/) if you'd like to try for yourself. 

**Desktop (please complete the following information):**
 - OS: [macOS 11.2.1]
 - Version [1.95]

**Comment by rsquizz** [comment]
I opened the .txt transcriptions and realized that CLOx didn't transcribe the whole thing either time. For Zou_Interview_Audio.mp4, it only transcribed the first 3 mins and 22 seconds. For Parkinson_Interview_Audio.mp4, it only transcribed the first 34 seconds the first time and the first 6 mins and 2 seconds the second time. I tried shutting off my internet and transcribing the Parkinson file a third time, and CLOx transcribed the first 4 minutes and 48 seconds. 

When I exported the transcript with timestamps, there were also jumps in the timestamps that don't match the recording. For example, in the attached .xlsx (converted from .csv because Github won't allow me to upload a .csv here), there's a jump from row 78's timestamp of 32.57 to row 79's timestamp of 66.53, but there's no gap either in the recording or in what was successfully transcribed from the recording at that point.

Do you have any thoughts as to what could be going on?

[Parkinson_transcript_2.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6079794/Parkinson_transcript_2.txt)

[Parkinson_transcript_2.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6079795/Parkinson_transcript_2.xlsx)

**Comment by campionfellin** [comment]
Hey Rob,

Good callout here... seems like I was doing some weird time compounding for each phrase. How does this look?

[parkinson.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6120763/parkinson.txt)

**Comment by campionfellin** [comment]
Should be fixed in version 1.100. Please let me know and I'll close this one out!

**Comment by rsquizz** [comment]
I tried transcribing Zou_interview_Audio.mp4 and Parkinson_Interview_Audio.mp4 twice each, and exported the .txt and .csv (without confidence level) each time. I haven't gone through and checked these transcripts word for word, since they're quite long, but I can at least open the last 10 seconds of the audio files and make sure that the transcriptions finished. I ran into problems with both transcripts.

For the first pass of the Zou interview, CLOx only transcribed the first 1370 words, but it transcribed the whole thing the second time.
[zou_transcript_1100_1_csv.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6134102/zou_transcript_1100_1_csv.xlsx)
[zou_transcript_1100_1.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6134103/zou_transcript_1100_1.txt)
[zou_transcript_1100_2_csv.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6134106/zou_transcript_1100_2_csv.xlsx)
[zou_transcript_1100_2.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6134107/zou_transcript_1100_2.txt)

For the first pass of the Parkinson interview, the .csv transcription was complete, but the .txt transcription missed the last 97 words (of 3087 total). The transcription finished completely on the second try.

[Parkinson_transcript_1100_1.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6134099/Parkinson_transcript_1100_1.txt)
[Parkinson_transcript_1100_csv_1.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6134100/Parkinson_transcript_1100_csv_1.xlsx)
[Parkinson_transcript_1100_2.txt](https://github.com/campionfellin/CLOxIssueTracker/files/6134119/Parkinson_transcript_1100_2.txt)
[Parkinson_transcript_1100_2_csv.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6134120/Parkinson_transcript_1100_2_csv.xlsx)

Not sure if these things matter, but

1. I don't think I was consistent about whether I converted the numbers to text before exporting, and
2. I didn't realize that CLOx v. 1.101 was out, so I've been using v. 1.100.

**Comment by campionfellin** [comment]
I'm glad at least it's giving you more-or-less the whole transcription! Weird that it takes a couple tries..

Version 1.101 is just a new way of exporting at the phrase level (or at least at the transcription-result level - the chunks Apple returns them in)

**Comment by rsquizz** [comment]
Replaced by #15.
