### ISSUE TITLE
[macOS] Feature request - how users can support us

### ISSUE THREAD

**Issue by rsquizz** [campionfellin/CLOxIssueTracker#12]
Since we are providing a free service, I was thinking that some of our users might be interested in or willing to give back to the project. Ideas for how users could do this:

-Rate and review CLOx on the App Store so that more people learn about and use CLOx
-Cite us in their academic work, both so that more people learn about and use CLOx and because it could help my (our?) career(s)

Other ideas? Maybe we could add a tab, "Support CLOx," or something?

**Comment by campionfellin** [comment]
Asked for a rating in version 1.96.

Can you let me know what wording you want to use to ask people to cite?

**Comment by rsquizz** [comment]
So if you're asking about the format of the citations, I'd keep the same wording as in the pdf guide (below) for now, and we can talk about updating the citation using version numbers at a later time. If you're asking about the language to use to ask people to cite us, what do you think of this?

CLOx is available free of charge. Please consider supporting us by rating and reviewing CLOx on the App Store. If you use CLOx for academic work, please cite us! You can cite CLOx using either of the formats below:

Wassink, A.B., Squizzero, R., Fellin, C. & Nichols, D. (2018). Client Libraries Oxford (CLOx): automated transcription for sociolinguistic interviews [computer software]. https://clox.ling.washington.edu. 

Wassink, A.B., Squizzero, R., Fellin, C. & Nichols, D. (2018, October). CLOx: Time-saving automated orthographic transcription tool for sociolinguistic interviews. Workshop given at New Ways of  Analyzing Variation 47, New York, NY.

**Comment by campionfellin** [comment]
This looks great! I can copy that onto the page in the next version.

**Comment by campionfellin** [comment]
Released in 1.97
