### ISSUE TITLE
[macOS] Possible memory leak - high RAM & CPU use when CLOx is idle

### ISSUE THREAD

**Issue by rsquizz** [campionfellin/CLOxIssueTracker#13]
After finishing two 20-minute offline transcriptions and walking away for ~30 minutes, I came back and noticed that my MacBook Air's fan was running, which is rare unless I'm doing something computationally intensive. Activity Monitor showed that the highest CPU and memory use was a process named com.apple.siri.embeddedspeech. Closing CLOx caused the CPU and memory use to drop significantly, and the fan shut off after a couple of minutes. Is it possible that there is a memory leak or similar issue? 

CLOx v. 1.95
macOS v. 11.2.1 (Big Sur)

Note: If I open CLOx, don't run any transcriptions, and leave it idle, I don't get this problem.

**Comment by campionfellin** [comment]
I think this issue and https://github.com/campionfellin/CLOxIssueTracker/issues/11 are related and I've seen issues like this before with super long files. I think there is an issue either in my code, or with Apple, where it marks the transcription as "done" when really it is not.

Thus, you'll get, like pointed out in https://github.com/campionfellin/CLOxIssueTracker/issues/11, incomplete transcripts, while simultaneously getting what you are reporting here.

I have noticed this before and have put off looking into this for a while, but I'll try to figure it out soon. I think I just need to figure out the right signal for when it is considered "done".

**Comment by rsquizz** [comment]
The memory leak part of this problem seems to be fixed for me, after some limited testing.

**Comment by campionfellin** [comment]
I think I fixed this with https://github.com/campionfellin/CLOxIssueTracker/issues/11. Basically - you were experiencing the intense resource usage because it was likely actually still running the transcription. Now that I've got the end-time / finalization code figured out, it should _actually_ end when it says it ends.

We can keep this open for a bit and close if it doesn't pop up again

**Comment by rsquizz** [comment]
I haven't encountered this problem after several transcription attempts, on several days, with several versions of CLOx. We can reopen if needed.
