### ISSUE TITLE
[macOS] Stripping commas from text before writing to csv

### ISSUE THREAD

**Issue by rsquizz** [campionfellin/CLOxIssueTracker#14]
**Describe the bug**
Not all the commas are being stripped from the text field of the transcription

**To Reproduce**
1. Transcribe the Parkinson interview file
2. Export phrases to csv
3. Scroll down to lines 22 and 35
4. See error (easiest to see in Excel)

**Desktop (please complete the following information):**
 - macOS: 11.2.3
 - Version 1.101

**Additional context**
[Parkinson_phrases_csv.xlsx](https://github.com/campionfellin/CLOxIssueTracker/files/6135771/Parkinson_phrases_csv.xlsx)

**Comment by campionfellin** [comment]
Fix released in 1.103.
