### ISSUE TITLE
[Web App] Link to Microsoft's guide on obtaining API key is broken

### ISSUE THREAD

**Issue by rsquizz** [campionfellin/CLOxIssueTracker#16]
On p. 4 of the CLOx web app's guide, the link to Microsoft's guide on how to obtain your API key is broken. The guide has been fixed but not yet deployed to the web. In the meantime, here is the link:
[https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview#try-the-speech-service-for-free](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview#try-the-speech-service-for-free)

**Comment by campionfellin** [comment]
@rsquizz I just need to update the PDF as a whole. Is this the right one to download? https://campionfellin.github.io/CLOx_2/CLOx_Guide.pdf

**Comment by rsquizz** [comment]
@campionfellin I've already updated it and uploaded and committed the new version to the CLOx_2 repo, but I don't know what David's workload is like at the moment or when he'll have a chance to deploy it. I'm just putting this here as a tip for any users who tried to access the link and couldn't.

**Comment by campionfellin** [comment]
Fixed in 1.104 of the macOS App.

**Comment by rsquizz** [comment]
> Fixed in 1.104 of the macOS App.

Was it broken in the macOS App?

**Comment by campionfellin** [comment]
No, good catch. Just submitted 1.105 to switch back to the Mac-specific guide.

**Comment by rsquizz** [comment]
The fix has been deployed
