### ISSUE TITLE
[macOS or Web App] Feature request: No rounding for time stamps

### ISSUE THREAD

**Issue by sebsau** [campionfellin/CLOxIssueTracker#17]
CLOx is great and will be of great use for researchs in psycholinguistics who study sentence and word production. The onset and offset times are currently rounded to 2 digits (giving it a resolution of 10 ms). Would it be possible to out put the time stamps either without rounding or with 3 or 4 digits? Then CLOx could be used to determine onsets and offsets of utterances in chronometric studies that compare onset times and durations between experimental conditions.

**Comment by campionfellin** [comment]
This seems pretty reasonable, users can round in Excel later if they so desire. Will pick this up next!

**Comment by campionfellin** [comment]
Hey @sebsau this is now done for version 1.106 of the macOS app. The changes are ready for the Web App but may take a couple of weeks to actually deploy.

I hope that works for you! I would really appreciate if you could give a 5 star rating and write a review in the App Store! Thanks!

**Comment by rsquizz** [comment]
This change has been deployed
